#include <stdio.h>
#include <stdlib.h>

float elec(float tot_elec, float renew_elec); //initializing the function for electricity

float ppr(float paper, float rec_ppr); //initializing the function for papers

float waste_rem(float rec_waste, float waste, float w_waste); //initializing the function for waste

float cfp(float n_elec, float unrec_f_ppr, float ur_waste); //initializing the function for carbon footprint

int main()

{
  printf("This is a program to calculate the no. of resources used by an institute.\nPls. enter values considering resources used for a month.");

float tot_elec, renew_elec, m_elec;  //initializing the total electricity & renewable electricity
printf("\n\nEnter the details for electricity consumption:\n\nEnter total units of electricity used in a month (Renewable and from mains too!)[eg. 123units]: ");
scanf("%f", &tot_elec);
printf("\nEnter the total units of renewable energy used (For eg. Solar, wind.)\n[eg. 56units, remember the value must be less than total usage] : ");
scanf("%f", &renew_elec);
m_elec = elec(tot_elec, renew_elec);

float trees, paper, rec_ppr, rec_u_ppr, fr_ppr, unrec_f_ppr; //initializing the total amount of papers used , recycled papers & fresh papers
printf("\n\nEnter the details for paper consumption: \nEnter the amount of paper used (in kgs. | total consumption) [eg. 123] : ");
scanf("%f", &paper);
printf("\n\nEnter the amount of recycled paper used \n[eg. 45, remember value must be less than total usage]: ");
scanf("%f", &rec_ppr);
printf("\nHow much paper goes into recycling [eg. 45, remember value must be less than or equal to the total usage] : ");
scanf("%f", &rec_u_ppr);
trees = ppr(paper, rec_ppr);

float waste, rec_waste, w_waste, unrec_waste, unrec_d_waste; //initializing total waste, wet waste & dry unrecycled waste
int ans; //initializing the answer
printf("\n\nEnter the details for waste generated, \nEnter total amount of dry waste generated (in kgs.) : ");
scanf("%f", &waste);
printf("Amount of wet waste generated : ");
scanf("%f", &w_waste);
printf("\n\nIs all dry waste sent out for recycling? \nreply with '1 1' for yes and '0 0' for no: ");
scanf("%d", &ans);
if ( ans == 1)
unrec_d_waste = 0;
else
printf("Enter  the amount of waste sent out for recycling : ");
scanf("%f", &rec_waste);
unrec_d_waste = waste_rem(rec_waste, waste, w_waste);

float carb_fp;
carb_fp = cfp(m_elec, trees, unrec_d_waste);
printf("The total anount of carbon residues generated by your institute \nDirectly and indirectly) are : %f", carb_fp);
printf("\n \nTIPS:\nSwitch it Off: \n   Turn off the lights when natural light is sufficient and when you \nleave the room.It's that simple!\nClimate Control :\n     Keep your temperature system on a moderate setting while you're in the room. \nWasteful Windows : \n    Use your windows wisely! If your climate control system is on, shut them...\nif you need a little fresh air, turn off the heat or AC. \nMinimize Plug Load : \n   Cut down the number of appliances you are running and you will save big \non energy. For example, share your mini fridge with roommates and \nminimize the number of printers in your office. \nPhantom Power : \n    Did you know that many electronics continue using energy even when powered down? This is true of any charger, television, printer, etc. Use a power \nstrip to easily unplug these electronics when not in use. \nGive it a Rest : \n   Power your computer down when you're away. A computer turned off uses at \nleast 65 percent less energy than a computer left on or idle on a screen saver.\nTake the Stairs : \n    Use the stairs as often as possible. Elevators consume electricity. \nYou, on the other hand, do not.\nSwitch to CFLs :\n   Compact fluorescent light bulbs (CFLs) use 75 percent less energy \nthan incandescent and last up to 10 times longer. \nConserve Paper :\n    Print and copy on two sides, save single-sided pages for notes, and \nprint only what you need.\nRecycle :\n    Take a few steps to a recycling center in your building to deposit \naluminum cans, plastics, glass, office paper, newspaper, cardboard. Pickup of \noffice electronics, bulk metal and surplus furniture can be arranged by \ncontacting Facilities Work Management.\nPromote Reuse : \n    Donate used cell phones and chargers, furniture clothing and \ncleaning and school supplies.");

return 0;

}

float elec(float tot_elec, float renew_elec) //defining the function of electricity
{
float x; //initializing the x as the electricity supplied from mains
x = tot_elec - renew_elec; //substracting the total amount of electricity supplied by mains from amount of renewable electricity to get the amount of unrecycled papers
return (float)x; // returning x and trees to the main function
}

float ppr(float paper, float rec_ppr) //defining the function of papers
{
float x, trees; //initializing x as unrecycled papers & trees as no. of trees required for unrecycled papers
x = paper - rec_ppr; //substracting the total amount of papers from amount of recycled papers to get the amount of unrecycled papers
trees = x/30; //as one tree gives 30kg of papers. Therefore, trees required to plant is the amount of unrecycled paper divide by 30
return (float)trees; // returning x and trees to the main function
}

float waste_rem(float rec_waste, float waste, float w_waste) //defining the function of waste
{
float x; //initializing x as unrecycled dry waste
x = waste - rec_waste - w_waste;//substracting the total amount of waste from amount of recycled waste to get the amount of unrecycled waste
return (float)x;// returning x to the main function
}

float cfp(float m_elec, float trees, float unrec_d_waste)
{
float x;
x = trees*1.81;
x = x + (m_elec*0.93);
x= x + (unrec_d_waste*0.2);
return (float)x;
}
